config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root 'home#index'

  resources :events
  resources :users, only: [:show]
  resources :attendances, only: %i[create destroy]
  resources :attendings, only: %i[create destroy]
  resources :invites, only: %i[create destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attending.rb
# frozen_string_literal: true

class Attending < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  # Associations for attendees
  has_many :attendings, foreign_key: :attended_event_id, dependent: :destroy, inverse_of: :event
  has_many :attendees, through: :attendings, source: :attendee

  # Associations for invites
  has_many :invites, dependent: :destroy
  has_many :invitees, through: :invites, source: :invitee

  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  belongs_to :event
  belongs_to :inviter, class_name: 'User'
  belongs_to :invitee, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Invites
  has_many :invites, foreign_key: :inviter_id, inverse_of: :event, dependent: :destroy
  has_many :sent_invites, foreign_key: :inviter_id, class_name: 'Invite', dependent: :destroy, inverse_of: :inviter
  has_many :received_invites, foreign_key: :invitee_id, class_name: 'Invite', dependent: :destroy, inverse_of: :invitee

  # Events the user is attending
  has_many :attendings, foreign_key: :attended_event_id, dependent: :destroy, inverse_of: :event
  has_many :attended_events, through: :attendings, source: :attended_event

  # Events the user is attending
  has_many :attendances, foreign_key: :attendee_id, class_name: 'Attending', dependent: :destroy, inverse_of: :attendee

  # associates user_id with creator_id in events table and allows event.creator method
  has_many :events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy, inverse_of: :creator

  # Events the user has created
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event', dependent: :destroy, inverse_of: :creator
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/attendings_controller.rb
# frozen_string_literal: true

class AttendingsController < ApplicationController
  before_action :authenticate_user!

  def create
    event = Event.find(params[:event_id])

    if invite_only_blocked?(event)
      redirect_to event, alert: t('alerts.not_invited')
      return
    end

    event.attendees << current_user unless event.attendees.include?(current_user)

    redirect_to event, notice: t('alerts.attending')
  end

  private

  def invite_only_blocked?(event)
    event.private? && event.invitees.exclude?(current_user)
  end

  def destroy
    event = Event.find(params[:event_id])
    event.attendees.delete(current_user)
    redirect_to event, notice: t('alerts.not_attending')
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @events = Event.all
    render json: events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: t('alerts.created')
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: t('alerts.updated')
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: t('alerts.deleted')
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Create a Edit Event</h1>
<%= render 'form', event: @event %>
<%= link_to 'Back to Events', events_path %>
<%= link_to 'Back to Home', root_path %>
<%# app/views/events/_form.html.erb %>

app/views/events/index.html.erb
<h1>All Events</h1>

<%= link_to 'Create New Event', new_event_path %>

<ul>
  <% @events.each do |event| %>
    <li>
      <strong><%= link_to event.name, event_path(event) %></strong>
      on <%= event.date.strftime('%B %d, %Y') %> at <%= event.location %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>Create a New Event</h1>
<%= render 'form', event: @event %>
<%= link_to 'Back to Events', events_path %>
<%= link_to 'Back to Home', root_path %>
<%# app/views/events/_form.html.erb %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><strong>Date:</strong> <%= @event.date.strftime('%B %d, %Y') %></p>
<p><strong>Location:</strong> <%= @event.location %></p>
<p><strong>Created by:</strong> <%= @event.creator.email %></p>

<h3>Attendees:</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li>
  <% end %>
</ul>

<% if user_signed_in? %>
  <% if @event.attendees.include?(current_user) %>
    <%= button_to 'Leave Event', attending_path(event_id: @event.id), method: :delete %>
  <% elsif !@event.private? || @event.invitees.include?(current_user) %>
    <%= button_to 'Attend Event', attendings_path(event_id: @event.id), method: :post %>
  <% else %>
    <p>This event is private. You need an invitation to attend.</p>

  <% end %>
<% end %>

<%= link_to 'Back to Events', events_path %>
<%= link_to 'Edit Event', edit_event_path(@event) %>
<%= link_to 'Delete Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back to Home', root_path %>
<%# app/views/events/show.html.erb %>
<%# This file is responsible for displaying the details of a specific event %>

app/views/home/index.html.erb
<h1>Berlin + Events</h1>

<p>Welcome to the Berlin + Events app! This is a simple event management application where users can create, view, and attend events.</p>
<p>To get started, you can:</p>
<ul>
  <li><%= link_to 'View All Events', events_path %></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventsberlin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Profile</h1>

<h2>Created Events</h2>
<ul>
  <% @user.created_events.each do |event| %>
    <li><%= link_to event.name, event_path(event) %></li>
  <% end %>
</ul>

<h2>Attending Events</h2>
<ul>
  <% @user.attended_events.each do |event| %>
    <li><%= link_to event.name, event_path(event) %> - <%= event.date > Date.today ? "Upcoming" : "Past" %></li>
  <% end %>
</ul>
<%= link_to 'Edit Profile', edit_user_registration_path %>
<%= link_to 'Back to Home', root_path %>
<%= link_to 'Back to Events', events_path %>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>